### ISSUE TITLE
Make titles of some windows dynamic

### ISSUE THREAD

**Issue by chooseanother** [chooseanother/G4_SEP1Z_A20#5]
Add window tittle to home view

make dynamic title for:
- project view
- requirement view
- team member view
- task view

if its a new project/req/task the window title should reflect it, otherwise it should be a default descriptive window title

**Comment by helloItsBob** [comment]
Added the titles, but..
don't know how to make stuff dynamic

**Comment by chooseanother** [comment]
you can change the title of a window/view in the init/reset method of the viewcontroller

`root.setUserData("Some title here");`
